### ISSUE TITLE
Datasets not functioning until appdata is deleted manually

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/BHoM_Installer#38] opened 2020-03-23 19:43 UTC
#### Description:

Testing v3.1 Pre-Alpha LCA - Upon install, user must delete appdata BHoM folder for datasets to function. Additional odd behaviour includes not being able to delete any BHoM object from the grasshopper canvas.

#### How to replicate:

Install from the referenced installer without deleting your previous build appdata folder. Open Grasshopper and select any dataset. 

#### Test file(s):

FYI @enarhi @kayleighhoude

**Comment by IsakNaslundBh** [comment] 2020-03-24 12:53
Have tested this installer, and I do not have any issues. Will rebuild from master one more time and try the installer again, but everything is running fine on my end.

**Comment by FraserGreenroyd** [comment] 2020-03-25 10:01
I've also investigated this alongside @IsakNaslundBh and are of the opinion this may be a local issue for your machines in the states @michaelhoehn owing to switching between dev branches and installers. I cannot reproduce this issue either, so am closing this issue for now, but if the issue does continue please reopen with more information :smile:

**Closed by FraserGreenroyd** 2020-03-25 10:01 UTC
Labels: type:bug
